SELECT * FROM EMPLOYEES 
WHERE EMPLOYEE_ID BETWEEN 100 AND 105; 

SELECT * FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (151 , 152, 153, 154 , 155); 

SELECT * FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) LIKE 'P%';  

SELECT * FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) LIKE '%A'; 

SELECT * FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) LIKE '%A%'; 

SELECT * FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) LIKE '__E%'; 

SELECT * FROM EMPLOYEES 
WHERE MANAGER_ID IS NULL; 

SELECT * FROM EMPLOYEES 
WHERE MANAGER_ID IS NOT NULL;

INSERT INTO EMPLOYEES (
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
)
VALUES (
    207,
    'Mohamed',
    'Mekawy',
    'muhh@gmail.com',
    '01069067770',
    DATE '2008-02-03',
    'AC_ACCOUNT',
    10000,
    NULL,
    NULL,
    110
);

SELECT * FROM EMPLOYEES e 
WHERE e.JOB_ID ='AD_VP' OR e.JOB_ID ='IT_PROG' ;

SELECT * FROM EMPLOYEES
ORDER BY LAST_NAME; 

SELECT * FROM EMPLOYEES
ORDER BY HIRE_DATE desc; 

SELECT * FROM EMPLOYEES
ORDER BY DEPARTMENT_ID , SALARY DESC  ; 

SELECT LOWER(LAST_NAME) FROM EMPLOYEES ;

SELECT upper(FIRST_NAME) FROM EMPLOYEES ;

SELECT INITCAP(FIRST_NAME) first_Name ,INITCAP(LAST_NAME) Last_Name FROM EMPLOYEES ;

SELECT * FROM EMPLOYEES 
WHERE lower(LAST_NAME )='smith';






