SELECT TO_CHAR(SYSDATE ,'dd-MON-YYYY' ) CURRENT_date FROM DUAL; 

SELECT TO_CHAR(SYSDATE ,'FMMonth/YYYY' ) CURRENT_date FROM DUAL; 

SELECT TO_CHAR(12345.67,'99,999.99') FROM dual; 

SELECT TO_CHAR(e.SALARY ,'99,999$') FROM EMPLOYEES e ; 