CREATE TABLE STUDENTS (
    NAME  VARCHAR2(50),
    MARKS NUMBER(3)
);


INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Ahmed', 95);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Mohamed', 88);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Sara', 76);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Mona', 69);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Youssef', 82);

SELECT NAME, MARKS , CASE
         WHEN MARKS >= 90 THEN 'A'
         WHEN MARKS BETWEEN 80 AND 89 THEN 'B'
         WHEN MARKS BETWEEN 70 AND 79 THEN 'C'
         ELSE 'F'
       END "GRADES"
FROM STUDENTS;
