CREATE TABLE MANAGERS (
    ID NUMBER(4,0) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    AGE NUMBER(2,0),
    BIRTH_DATE DATE,
    ADDRESS VARCHAR2(200)
);

ALTER TABLE MANAGERS DROP COLUMN  ADDRESS ;

ALTER TABLE MANAGERS
ADD (
    CITY_ADDRESS VARCHAR2(100),
    STREET VARCHAR2(100)
);

ALTER TABLE MANAGERS RENAME COLUMN NAME TO FULL_NAME;

ALTER TABLE MANAGERS READ ONLY	;

CREATE TABLE OWNER AS
SELECT ID, FULL_NAME, BIRTH_DATE
FROM MANAGERS;

ALTER TABLE	MANAGERS RENAME TO	MASTER;

DROP TABLE MASTER;
DROP TABLE OWNER;