INSERT INTO MUHAMMED_MEKAWY.student VALUES (3, 'Ali');

SELECT *
FROM MUHAMMED_MEKAWY.student;

UPDATE MUHAMMED_MEKAWY.student
SET name = 'Omar'
WHERE id = 2;

DELETE FROM MUHAMMED_MEKAWY.student
WHERE id = 3;