CREATE TABLE EMP_TEST (
    NAME VARCHAR2(50)
); 

INSERT ALL
    INTO EMP_TEST (NAME) VALUES ('   Mohamed Mekawy   ')
    INTO EMP_TEST (NAME) VALUES ('   Ahmed Ali')
    INTO EMP_TEST (NAME) VALUES ('Sara Hassan   ')
    INTO EMP_TEST (NAME) VALUES ('   Omar Khaled   ')
    INTO EMP_TEST (NAME) VALUES ('Mona Ibrahim')
SELECT * FROM DUAL;

SELECT TRIM(NAME) FROM EMP_TEST ; 

SELECT LTRIM(NAME) FROM EMP_TEST; 

SELECT RTRIM(NAME) FROM EMP_TEST; 

INSERT INTO EMP_TEST (NAME) VALUES ('  #Mohamed#123  '); 

SELECT LTRIM(RTRIM(NAME, ' 0123456789#'), ' #') 
FROM EMP_TEST ;
